package com.example.demo3.mapper;

import com.example.demo3.model.NameList;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface NameListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table name
     *
     * @mbg.generated Thu Aug 01 11:04:56 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table name
     *
     * @mbg.generated Thu Aug 01 11:04:56 CST 2019
     */
    int insert(NameList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table name
     *
     * @mbg.generated Thu Aug 01 11:04:56 CST 2019
     */
    int insertSelective(NameList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table name
     *
     * @mbg.generated Thu Aug 01 11:04:56 CST 2019
     */
    NameList selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table name
     *
     * @mbg.generated Thu Aug 01 11:04:56 CST 2019
     */
    int updateByPrimaryKeySelective(NameList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table name
     *
     * @mbg.generated Thu Aug 01 11:04:56 CST 2019
     */
    int updateByPrimaryKey(NameList record);
}