package com.qld.springboot.bobo.mapper;

import com.qld.springboot.bobo.model.NameList;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface NameListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nl_ol_name_list
     *
     * @mbggenerated Thu Jul 11 20:39:55 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nl_ol_name_list
     *
     * @mbggenerated Thu Jul 11 20:39:55 CST 2019
     */
    int insert(NameList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nl_ol_name_list
     *
     * @mbggenerated Thu Jul 11 20:39:55 CST 2019
     */
    int insertSelective(NameList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nl_ol_name_list
     *
     * @mbggenerated Thu Jul 11 20:39:55 CST 2019
     */
    NameList selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nl_ol_name_list
     *
     * @mbggenerated Thu Jul 11 20:39:55 CST 2019
     */
    int updateByPrimaryKeySelective(NameList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nl_ol_name_list
     *
     * @mbggenerated Thu Jul 11 20:39:55 CST 2019
     */
    int updateByPrimaryKey(NameList record);

    List<NameList> selectAll();


}