package com.qld.springboot.bobo.model;

import java.io.Serializable;
import java.util.Date;

public class NameList implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nl_ol_name_list.id
     *
     * @mbggenerated Thu Jul 11 20:39:55 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nl_ol_name_list.UNIQUE_ID
     *
     * @mbggenerated Thu Jul 11 20:39:55 CST 2019
     */
    private String uniqueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nl_ol_name_list.NAME
     *
     * @mbggenerated Thu Jul 11 20:39:55 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nl_ol_name_list.STATUS
     *
     * @mbggenerated Thu Jul 11 20:39:55 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nl_ol_name_list.EXPIRES_DATE
     *
     * @mbggenerated Thu Jul 11 20:39:55 CST 2019
     */
    private Date expiresDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nl_ol_name_list.COMMENTS
     *
     * @mbggenerated Thu Jul 11 20:39:55 CST 2019
     */
    private String comments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nl_ol_name_list.SOURCE
     *
     * @mbggenerated Thu Jul 11 20:39:55 CST 2019
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nl_ol_name_list.TAG
     *
     * @mbggenerated Thu Jul 11 20:39:55 CST 2019
     */
    private String tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nl_ol_name_list.TYPE
     *
     * @mbggenerated Thu Jul 11 20:39:55 CST 2019
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nl_ol_name_list.CREATE_TIME
     *
     * @mbggenerated Thu Jul 11 20:39:55 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nl_ol_name_list.UPDATE_TIME
     *
     * @mbggenerated Thu Jul 11 20:39:55 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nl_ol_name_list.MODIFIER
     *
     * @mbggenerated Thu Jul 11 20:39:55 CST 2019
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table nl_ol_name_list
     *
     * @mbggenerated Thu Jul 11 20:39:55 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nl_ol_name_list.id
     *
     * @return the value of nl_ol_name_list.id
     * @mbggenerated Thu Jul 11 20:39:55 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nl_ol_name_list.id
     *
     * @param id the value for nl_ol_name_list.id
     * @mbggenerated Thu Jul 11 20:39:55 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nl_ol_name_list.UNIQUE_ID
     *
     * @return the value of nl_ol_name_list.UNIQUE_ID
     * @mbggenerated Thu Jul 11 20:39:55 CST 2019
     */
    public String getUniqueId() {
        return uniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nl_ol_name_list.UNIQUE_ID
     *
     * @param uniqueId the value for nl_ol_name_list.UNIQUE_ID
     * @mbggenerated Thu Jul 11 20:39:55 CST 2019
     */
    public void setUniqueId(String uniqueId) {
        this.uniqueId = uniqueId == null ? null : uniqueId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nl_ol_name_list.NAME
     *
     * @return the value of nl_ol_name_list.NAME
     * @mbggenerated Thu Jul 11 20:39:55 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nl_ol_name_list.NAME
     *
     * @param name the value for nl_ol_name_list.NAME
     * @mbggenerated Thu Jul 11 20:39:55 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nl_ol_name_list.STATUS
     *
     * @return the value of nl_ol_name_list.STATUS
     * @mbggenerated Thu Jul 11 20:39:55 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nl_ol_name_list.STATUS
     *
     * @param status the value for nl_ol_name_list.STATUS
     * @mbggenerated Thu Jul 11 20:39:55 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nl_ol_name_list.EXPIRES_DATE
     *
     * @return the value of nl_ol_name_list.EXPIRES_DATE
     * @mbggenerated Thu Jul 11 20:39:55 CST 2019
     */
    public Date getExpiresDate() {
        return expiresDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nl_ol_name_list.EXPIRES_DATE
     *
     * @param expiresDate the value for nl_ol_name_list.EXPIRES_DATE
     * @mbggenerated Thu Jul 11 20:39:55 CST 2019
     */
    public void setExpiresDate(Date expiresDate) {
        this.expiresDate = expiresDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nl_ol_name_list.COMMENTS
     *
     * @return the value of nl_ol_name_list.COMMENTS
     * @mbggenerated Thu Jul 11 20:39:55 CST 2019
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nl_ol_name_list.COMMENTS
     *
     * @param comments the value for nl_ol_name_list.COMMENTS
     * @mbggenerated Thu Jul 11 20:39:55 CST 2019
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nl_ol_name_list.SOURCE
     *
     * @return the value of nl_ol_name_list.SOURCE
     * @mbggenerated Thu Jul 11 20:39:55 CST 2019
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nl_ol_name_list.SOURCE
     *
     * @param source the value for nl_ol_name_list.SOURCE
     * @mbggenerated Thu Jul 11 20:39:55 CST 2019
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nl_ol_name_list.TAG
     *
     * @return the value of nl_ol_name_list.TAG
     * @mbggenerated Thu Jul 11 20:39:55 CST 2019
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nl_ol_name_list.TAG
     *
     * @param tag the value for nl_ol_name_list.TAG
     * @mbggenerated Thu Jul 11 20:39:55 CST 2019
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nl_ol_name_list.TYPE
     *
     * @return the value of nl_ol_name_list.TYPE
     * @mbggenerated Thu Jul 11 20:39:55 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nl_ol_name_list.TYPE
     *
     * @param type the value for nl_ol_name_list.TYPE
     * @mbggenerated Thu Jul 11 20:39:55 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nl_ol_name_list.CREATE_TIME
     *
     * @return the value of nl_ol_name_list.CREATE_TIME
     * @mbggenerated Thu Jul 11 20:39:55 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nl_ol_name_list.CREATE_TIME
     *
     * @param createTime the value for nl_ol_name_list.CREATE_TIME
     * @mbggenerated Thu Jul 11 20:39:55 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nl_ol_name_list.UPDATE_TIME
     *
     * @return the value of nl_ol_name_list.UPDATE_TIME
     * @mbggenerated Thu Jul 11 20:39:55 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nl_ol_name_list.UPDATE_TIME
     *
     * @param updateTime the value for nl_ol_name_list.UPDATE_TIME
     * @mbggenerated Thu Jul 11 20:39:55 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nl_ol_name_list.MODIFIER
     *
     * @return the value of nl_ol_name_list.MODIFIER
     * @mbggenerated Thu Jul 11 20:39:55 CST 2019
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nl_ol_name_list.MODIFIER
     *
     * @param modifier the value for nl_ol_name_list.MODIFIER
     * @mbggenerated Thu Jul 11 20:39:55 CST 2019
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nl_ol_name_list
     *
     * @mbggenerated Thu Jul 11 20:39:55 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        NameList other = (NameList) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getUniqueId() == null ? other.getUniqueId() == null : this.getUniqueId().equals(other.getUniqueId()))
                && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
                && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
                && (this.getExpiresDate() == null ? other.getExpiresDate() == null : this.getExpiresDate().equals(other.getExpiresDate()))
                && (this.getComments() == null ? other.getComments() == null : this.getComments().equals(other.getComments()))
                && (this.getSource() == null ? other.getSource() == null : this.getSource().equals(other.getSource()))
                && (this.getTag() == null ? other.getTag() == null : this.getTag().equals(other.getTag()))
                && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
                && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
                && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
                && (this.getModifier() == null ? other.getModifier() == null : this.getModifier().equals(other.getModifier()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nl_ol_name_list
     *
     * @mbggenerated Thu Jul 11 20:39:55 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUniqueId() == null) ? 0 : getUniqueId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getExpiresDate() == null) ? 0 : getExpiresDate().hashCode());
        result = prime * result + ((getComments() == null) ? 0 : getComments().hashCode());
        result = prime * result + ((getSource() == null) ? 0 : getSource().hashCode());
        result = prime * result + ((getTag() == null) ? 0 : getTag().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getModifier() == null) ? 0 : getModifier().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nl_ol_name_list
     *
     * @mbggenerated Thu Jul 11 20:39:55 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uniqueId=").append(uniqueId);
        sb.append(", name=").append(name);
        sb.append(", status=").append(status);
        sb.append(", expiresDate=").append(expiresDate);
        sb.append(", comments=").append(comments);
        sb.append(", source=").append(source);
        sb.append(", tag=").append(tag);
        sb.append(", type=").append(type);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", modifier=").append(modifier);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}