package spring.springboot.model;

import java.util.Date;

public class NameList {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nl_ol_name_list.id
     *
     * @mbg.generated Fri Jul 12 09:58:40 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nl_ol_name_list.UNIQUE_ID
     *
     * @mbg.generated Fri Jul 12 09:58:40 CST 2019
     */
    private String uniqueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nl_ol_name_list.NAME
     *
     * @mbg.generated Fri Jul 12 09:58:40 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nl_ol_name_list.STATUS
     *
     * @mbg.generated Fri Jul 12 09:58:40 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nl_ol_name_list.EXPIRES_DATE
     *
     * @mbg.generated Fri Jul 12 09:58:40 CST 2019
     */
    private Date expiresDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nl_ol_name_list.COMMENTS
     *
     * @mbg.generated Fri Jul 12 09:58:40 CST 2019
     */
    private String comments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nl_ol_name_list.SOURCE
     *
     * @mbg.generated Fri Jul 12 09:58:40 CST 2019
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nl_ol_name_list.TAG
     *
     * @mbg.generated Fri Jul 12 09:58:40 CST 2019
     */
    private String tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nl_ol_name_list.TYPE
     *
     * @mbg.generated Fri Jul 12 09:58:40 CST 2019
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nl_ol_name_list.CREATE_TIME
     *
     * @mbg.generated Fri Jul 12 09:58:40 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nl_ol_name_list.UPDATE_TIME
     *
     * @mbg.generated Fri Jul 12 09:58:40 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nl_ol_name_list.MODIFIER
     *
     * @mbg.generated Fri Jul 12 09:58:40 CST 2019
     */
    private String modifier;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nl_ol_name_list.id
     *
     * @return the value of nl_ol_name_list.id
     * @mbg.generated Fri Jul 12 09:58:40 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nl_ol_name_list.id
     *
     * @param id the value for nl_ol_name_list.id
     * @mbg.generated Fri Jul 12 09:58:40 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nl_ol_name_list.UNIQUE_ID
     *
     * @return the value of nl_ol_name_list.UNIQUE_ID
     * @mbg.generated Fri Jul 12 09:58:40 CST 2019
     */
    public String getUniqueId() {
        return uniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nl_ol_name_list.UNIQUE_ID
     *
     * @param uniqueId the value for nl_ol_name_list.UNIQUE_ID
     * @mbg.generated Fri Jul 12 09:58:40 CST 2019
     */
    public void setUniqueId(String uniqueId) {
        this.uniqueId = uniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nl_ol_name_list.NAME
     *
     * @return the value of nl_ol_name_list.NAME
     * @mbg.generated Fri Jul 12 09:58:40 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nl_ol_name_list.NAME
     *
     * @param name the value for nl_ol_name_list.NAME
     * @mbg.generated Fri Jul 12 09:58:40 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nl_ol_name_list.STATUS
     *
     * @return the value of nl_ol_name_list.STATUS
     * @mbg.generated Fri Jul 12 09:58:40 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nl_ol_name_list.STATUS
     *
     * @param status the value for nl_ol_name_list.STATUS
     * @mbg.generated Fri Jul 12 09:58:40 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nl_ol_name_list.EXPIRES_DATE
     *
     * @return the value of nl_ol_name_list.EXPIRES_DATE
     * @mbg.generated Fri Jul 12 09:58:40 CST 2019
     */
    public Date getExpiresDate() {
        return expiresDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nl_ol_name_list.EXPIRES_DATE
     *
     * @param expiresDate the value for nl_ol_name_list.EXPIRES_DATE
     * @mbg.generated Fri Jul 12 09:58:40 CST 2019
     */
    public void setExpiresDate(Date expiresDate) {
        this.expiresDate = expiresDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nl_ol_name_list.COMMENTS
     *
     * @return the value of nl_ol_name_list.COMMENTS
     * @mbg.generated Fri Jul 12 09:58:40 CST 2019
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nl_ol_name_list.COMMENTS
     *
     * @param comments the value for nl_ol_name_list.COMMENTS
     * @mbg.generated Fri Jul 12 09:58:40 CST 2019
     */
    public void setComments(String comments) {
        this.comments = comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nl_ol_name_list.SOURCE
     *
     * @return the value of nl_ol_name_list.SOURCE
     * @mbg.generated Fri Jul 12 09:58:40 CST 2019
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nl_ol_name_list.SOURCE
     *
     * @param source the value for nl_ol_name_list.SOURCE
     * @mbg.generated Fri Jul 12 09:58:40 CST 2019
     */
    public void setSource(String source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nl_ol_name_list.TAG
     *
     * @return the value of nl_ol_name_list.TAG
     * @mbg.generated Fri Jul 12 09:58:40 CST 2019
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nl_ol_name_list.TAG
     *
     * @param tag the value for nl_ol_name_list.TAG
     * @mbg.generated Fri Jul 12 09:58:40 CST 2019
     */
    public void setTag(String tag) {
        this.tag = tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nl_ol_name_list.TYPE
     *
     * @return the value of nl_ol_name_list.TYPE
     * @mbg.generated Fri Jul 12 09:58:40 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nl_ol_name_list.TYPE
     *
     * @param type the value for nl_ol_name_list.TYPE
     * @mbg.generated Fri Jul 12 09:58:40 CST 2019
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nl_ol_name_list.CREATE_TIME
     *
     * @return the value of nl_ol_name_list.CREATE_TIME
     * @mbg.generated Fri Jul 12 09:58:40 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nl_ol_name_list.CREATE_TIME
     *
     * @param createTime the value for nl_ol_name_list.CREATE_TIME
     * @mbg.generated Fri Jul 12 09:58:40 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nl_ol_name_list.UPDATE_TIME
     *
     * @return the value of nl_ol_name_list.UPDATE_TIME
     * @mbg.generated Fri Jul 12 09:58:40 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nl_ol_name_list.UPDATE_TIME
     *
     * @param updateTime the value for nl_ol_name_list.UPDATE_TIME
     * @mbg.generated Fri Jul 12 09:58:40 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nl_ol_name_list.MODIFIER
     *
     * @return the value of nl_ol_name_list.MODIFIER
     * @mbg.generated Fri Jul 12 09:58:40 CST 2019
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nl_ol_name_list.MODIFIER
     *
     * @param modifier the value for nl_ol_name_list.MODIFIER
     * @mbg.generated Fri Jul 12 09:58:40 CST 2019
     */
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }
}